port: 8001
database:
  driver: "mysql"
  host: "Localhost"
  port: "3306"
  user: "zafiranur"
  password: "sabila123"
  db_name: "digitalent_microservice_auth"
  config: "charset=utf8&parseTime=True&loc=local"